endpoint: "http://localhost:9000"
region: "us-east-1" # Optional, but often needed for AWS SDK
bucket: "flumen"
accessKey: "minioadmin"
secretKey: "minioadmin"
putObjectSizeKB: 1024 # Size of objects to upload in KB for "write" or "mixed" mode (default: 1024)
generateManifest: true
operationType: "write" # Options: "write", "read", "mixed"
fileCount: 10000
# Logging configuration
logLevel: "debug" # Log level: debug, info, warn, error (default: info)